version: "3.9"

services:
  recipe_book_backend:
    image: jamesdimonaco/recipe_book_backend:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RUST_BACKTRACE: "full"
      RUST_LOG: "info"
    env_file:
      - .env
    ports:
      - "3232:3232"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3232 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
