name: Deploy Backend
on:
  push:
    branches:
      - main
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build  --platform linux/arm/v8 -t recipe_book_backend .
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Tag
        run: docker tag backend ${{ secrets.DOCKER_USERNAME }}/recipe_book_backend:latest
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/recipe_book_backend
