name: Deploy Backend
on:
  push:
    branches:
      - main
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v1
      - name: Docker Buildx Build
        run: docker buildx build --platform linux/arm/v8 -t recipe_book_backend:latest ./backend --push
  SSH-Deploy:
    runs-on: ubuntu-latest
    needs: Docker-Build-Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
          cd recipe_book_backend/
          docker-compose pull
          docker-compose up --remove-orphans -d
          ENDSSH
